version: '1.0'
name: pipeline-20220623
displayName: DEV文档
triggers:
  trigger: manual
  push:
    branches:
      prefix:
        - ''
stages:
  - name: stage-20cbbf31
    displayName: 未命名
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: Nodejs 构建
        nodeVersion: 16.14.2
        commands:
          - npm install -g pnpm && pnpm i && pnpm run "docs:build"
        artifacts:
          - name: DOCS
            path:
              - ./docs/.vuepress/dist
        caches:
          - ~/.npm
          - ~/.yarn
        strategy:
          retry: '0'
      - step: deploy@agent
        name: deploy_agent
        displayName: 主机部署
        hostGroupID: aliyun
        deployArtifact:
          - source: build
            name: dist
            target: /opt/test
            dependArtifact: DOCS
        script: |-
          # 请在此输入部署脚本，如启动Java应用如下
          # nohup java -jar test.jar > nohup.out &
           echo 'Hello Gitee!'
        strategy:
          retry: '0'
        dependsOn: build_nodejs
permissions:
  - role: admin
    members: []
