name: Build Vue3 Docs

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@646cdf48217256a3d0b80361c5a50727664284f2
      with:
        version: 7.27.0

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'pnpm'

    - name: Build
      run: |
        pnpm i
        pnpm run docs:build
        
    - name: Upload GitHub Pages artifact
      uses: actions/upload-pages-artifact@v1.0.7
      with:
        # Artifact name
        name: github-pages
        # Path of the directory containing the static assets.
        path: docs/.vuepress/dist
        # Duration after which artifact will expire in days.
        retention-days: 1
    - name: Deploy GitHub Pages site
      uses: actions/deploy-pages@v1.2.4
      with:
        # Should this action only emit build telemetry instead of deploying the build artifact?
        emit_telemetry: false
        # The status of the previous build.
        # conclusion: # optional
        # GitHub token
        token: ${{ TOKEN }}
        # Time in milliseconds after which to timeout and cancel the deployment (default: 10 minutes)
        # timeout: # optional, default is 600000
        # Maximum number of status report errors before cancelling a deployment (default: 10)
        # error_count: # optional, default is 10
        # Time in milliseconds between two deployment status report (default: 5 seconds)
        # reporting_interval: # optional, default is 5000
        # Name of the artifact to deploy
        artifact_name: github-pages
        # Is this attempting to deploy a pull request as a GitHub Pages preview site? (NOTE: This feature is only in alpha currently and is not available to the public!)
        preview: false
        
